### PR TITLE
Use Java 11 - required for CloudStack 4.14

### PR DESCRIPTION
**Pull request by olivierlemasle**
Use JDK 11, as it is required by CloudStack 4.14 (cf https://github.com/apache/cloudstack/pull/3601)

### CODE REVIEW

**Review by khos2ow — COMMENTED** [review]
Thank @olivierlemasle. The problem with this change is that it breaks backward compatibility and folks out there might still be on older version of CloudStack (considering that JDK 11 is enabled on 4.14+), so instead of modifying this file I'd suggest renaming it to `centos7/Dockerfile.jdk8` and create a new file with your changes as `centos7/Dockerfile.jdk11`.

Also I just updated the CI config, if you can rebase and adjust Makefile and README that'd be awesome otherwise I can proceed with your PR and update them later.

**Comment by khos2ow** [comment]
And for that matter I'm thinking of the following images:

- `latest`, `latest-jdk8`, `centos7`, `centos7-jdk8` (centos7/Dockerfile.jdk8)
- `latest-jdk11`, `centos7-jdk11` (centos7/Dockerfile.jdk11)
- `centos6` (centos6/Dockerfile)

What do you think?

**Comment by olivierlemasle** [comment]
Yes, sounds good!
I'll do that.

**Comment by olivierlemasle** [comment]
Rebased and adapted to propose both JDK 8 and JDK 11.

**Review by khos2ow — APPROVED** [review]

**Comment by khos2ow** [comment]
Thank you @olivierlemasle :+1:

**Pull request merged**
